<center><h3>Régression linéaire multiple<h3></center>

In [18]:
#Importation des bibiotheques

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import  accuracy_score, mean_absolute_error, mean_squared_error
import numpy as np

In [19]:
StartupsData = pd.read_csv("./../../Datasets/50_Startups.csv")

StartupsData.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

<center>Prétraitement des données</center>

In [20]:
StartupsData.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

Verification que chaque colonne ne contient pas de valeurs manquantes

In [21]:
StartupsData["R&D Spend"].isna().sum()

0

In [22]:
StartupsData["Administration"].isna().sum()

0

In [23]:
StartupsData["Marketing Spend"].isna().sum()

0

In [24]:
StartupsData["State"].isna().sum()

0

In [25]:
StartupsData["Profit"].isna().sum()

0

encodage de la colonne State avec le OneHotEncoder

In [29]:
from sklearn.preprocessing import OneHotEncoder

oneHotEncoder = OneHotEncoder()

StartupsData["State"] = oneHotEncoder.fit_transform(StartupsData.loc[:, ["State"]]).toarray()

In [30]:
StartupsData

R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.20       136897.80        471784.10    0.0  192261.83
1   162597.70       151377.59        443898.53    1.0  191792.06
2   153441.51       101145.55        407934.54    0.0  191050.39
3   144372.41       118671.85        383199.62    0.0  182901.99
4   142107.34        91391.77        366168.42    0.0  166187.94
5   131876.90        99814.71        362861.36    0.0  156991.12
6   134615.46       147198.87        127716.82    1.0  156122.51
7   130298.13       145530.06        323876.68    0.0  155752.60
8   120542.52       148718.95        311613.29    0.0  152211.77
9   123334.88       108679.17        304981.62    1.0  149759.96
10  101913.08       110594.11        229160.95    0.0  146121.95
11  100671.96        91790.61        249744.55    1.0  144259.40
12   93863.75       127320.38        249839.44    0.0  141585.52
13   91992.39       135495.07        252664.93    1.0  134307.35
14  119943.24       156547.42        256512.92    0.0  132602.65
15  114523.61       122616.84        261776.23    0.0  129917.04
16   78013.11       121597.55        264346.06    1.0  126992.93
17   94657.16       145077.58        282574.31    0.0  125370.37
18   91749.16       114175.79        294919.57    0.0  124266.90
19   86419.70       153514.11             0.00    0.0  122776.86
20   76253.86       113867.30        298664.47    1.0  118474.03
21   78389.47       153773.43        299737.29    0.0  111313.02
22   73994.56       122782.75        303319.26    0.0  110352.25
23   67532.53       105751.03        304768.73    0.0  108733.99
24   77044.01        99281.34        140574.81    0.0  108552.04
25   64664.71       139553.16        137962.62    1.0  107404.34
26   75328.87       144135.98        134050.07    0.0  105733.54
27   72107.60       127864.55        353183.81    0.0  105008.31
28   66051.52       182645.56        118148.20    0.0  103282.38
29   65605.48       153032.06        107138.38    0.0  101004.64
30   61994.48       115641.28         91131.24    0.0   99937.59
31   61136.38       152701.92         88218.23    0.0   97483.56
32   63408.86       129219.61         46085.25    1.0   97427.84
33   55493.95       103057.49        214634.81    0.0   96778.92
34   46426.07       157693.92        210797.67    1.0   96712.80
35   46014.02        85047.44        205517.64    0.0   96479.51
36   28663.76       127056.21        201126.82    0.0   90708.19
37   44069.95        51283.14        197029.42    1.0   89949.14
38   20229.59        65947.93        185265.10    0.0   81229.06
39   38558.51        82982.09        174999.30    1.0   81005.76
40   28754.33       118546.05        172795.67    1.0   78239.91
41   27892.92        84710.77        164470.71    0.0   77798.83
42   23640.93        96189.63        148001.11    1.0   71498.49
43   15505.73       127382.30         35534.17    0.0   69758.98
44   22177.74       154806.14         28334.72    1.0   65200.33
45    1000.23       124153.04          1903.93    0.0   64926.08
46    1315.46       115816.21        297114.46    0.0   49490.75
47       0.00       135426.92             0.00    1.0   42559.73
48     542.05        51743.15             0.00    0.0   35673.41
49       0.00       116983.80         45173.06    1.0   14681.40

Nous n'aurons pas besoin de normaliser les données ici catr il s'agit d'une regression linéaire et les libraries le feront pour nous

In [31]:
X = StartupsData.iloc[:, :-1].values
Y = StartupsData.iloc[:, 4].values

In [32]:
X

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 0.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 1.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 0.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 0.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 0.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 0.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 1.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 0.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 0.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 1.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 0.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 1.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 0.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 1.0000000e+00],
       [1.1994324e+05, 1.5654742e+

Séparation du jeu de données

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=0)

appliquons la regression linéaire multiple

In [42]:
from sklearn.linear_model import LinearRegression

linearRegression = LinearRegression()

linearRegression.fit(X_train, y_train)

LinearRegression()

Prédiction

In [46]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56])

In [47]:
y_pred = linearRegression.predict(X_test)

y_pred

array([103962.55391373, 132569.79621934, 133248.38608834,  72577.20448177,
       179058.65635572, 114748.39099366,  66688.37917583,  98150.25103157])

In [48]:
score = mean_squared_error(y_test, y_pred)
score

97581277.90779126

<center><h2>BackWard Élimination</h2></center>

<center>Appliquons le BackWard Élimination pour eliminer les variables qui n'ont pas un grand imapct sur la variable dependante profit</center>

In [70]:
import statsmodels.formula.api  as sm

Ici, on va concatener le dataset avec une colonne de 1 a la premeiere colonne du dataset pour que on ait quelque chose de la forme :

Y = b0*X0 + b1*X1 + b2*X2 + ... + bn*Xn

ou Xi est la  variable independante 
bi est le coefficient 
Y est la variable dependante

car au depat on avait:

Y = b0 + b1*X1 + b2*X2 + ... + bn*Xn 

et donc comme on veut avoir le cofficient de chaque vaiable independante, on a pensé a ajouter une colonne de 1 au debut du dataset qui serait equivaut a X0 pour qu'on aiyt l'expression:  

Y = b0*X0 + b1*X1 + b2*X2 + ... + bn*Xn

In [71]:
size = len(Y)

In [72]:
X = np.append( arr=np.ones((size, 1)).astype(int), values=X, axis=1 )
X

array([[1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.6534920e+05, 1.3689780e+05, 4.7178410e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.6259770e+05, 1.5137759e+05, 4.4389853e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.5344151e+05, 1.0114555e+05, 4.0793454e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.4437241e+05, 1.1867185e+05, 3.8319962e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.4210734e+05, 9.1391770e+04, 3.6616842e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.3187690e+05, 9.9814710e+04, 3.6286136e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 1.

In [ ]:
#Créons une matrice X_optimale qui contiuendra les variables qui apportent une importance siginificative a notre modele

X_optimale = X[:, [0, 1, 2, 3, 4, 5, 6]] #Recuperer toutes les colonnes du dataset X
X_optimale


array([[1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.6534920e+05, 1.3689780e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.6259770e+05, 1.5137759e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.5344151e+05, 1.0114555e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.4437241e+05, 1.1867185e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.4210734e+05, 9.1391770e+04],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.3187690e+05, 9.9814710e+04],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.3461546e+05, 1.4719887e+05],
       [1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.3029813e+05, 1.4553006e+05],
       [1.0000000e+00, 1

In [79]:
#Creons un nouveau modele de regression pour statmodel

regressor_OLS = sm.ols(endog = Y, exog = X_optimale).fit()
#ols originallly least squares

TypeError: Model.from_formula() missing 2 required positional arguments: 'formula' and 'data'