<center><h2>roadmap: pretraitement des données pour la datascience<h2></center>

<center>Charger les bibiotheques nécéssaire pour le pretraitement</center>

In [ ]:
import numpy as np #nécéssaire pour les calculs matriciels etc...
import pandas as pd #nécéssaire pour charger le jeu de données
import matplotlib.pyplot as plt #nécéssaire pour tracer des courbes et graphes

<center>Chargerment du dataset</center>

In [1]:
data = pd.read_csv("./../../Datasets/data.csv")

salaryData = pd.read_csv("./../../Datasets/salaryData.csv")

smoking = pd.read_csv("./../../Datasets/smoking.csv")

NameError: name 'pd' is not defined

<center>Cherchons les informations sur les datasets</center>

In [ ]:
data.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:
"""
Explications des lignes de du tableau renvoyé par data;describe()
-count : fait reference au nombre de valeur presente dans le dataset dans notre cas on a 9 age et 9 salaires dans notre jeu de données
-mean : represente la moyenne de chaque colonne ,ici age et salaire
-std : ecart-type 
-min : La valeur minimale
-25% : le premier quartile
-50% : le deuxieme quartile ou la mediane
-75% : Le troisieme quartile
-max : La valeur maximale de chaque colonne
"""

'\nExplications des lignes de du tableau renvoyé par data;describe()\n-count : fait reference au nombre de valeur presente dans le dataset dans notre cas on a 9 age et 9 salaires dans notre jeu de données\n-mean : represente la moyenne de chaque colonne ,ici age et salaire\n-std : ecart-type \n-min : La valeur minimale\n-25% : le premier quartile\n-50% : le deuxieme quartile ou la mediane\n-75% : Le troisieme quartile\n-max : La valeur maximale de chaque colonne\n'

In [ ]:
salaryData.describe()


YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [ ]:
smoking.describe()

age  amt_weekends  amt_weekdays
count  1691.000000    421.000000    421.000000
mean     49.836192     16.410926     13.750594
std      18.736851      9.892988      9.388292
min      16.000000      0.000000      0.000000
25%      34.000000     10.000000      7.000000
50%      48.000000     15.000000     12.000000
75%      65.500000     20.000000     20.000000
max      97.000000     60.000000     55.000000

<center>Affichage des 5 premieres lignes du dataset pour le visualiser </center>

In [ ]:
data.head(5)

Country   Age   Salary     Region Purchased
0   France  44.0  72000.0      ouest        No
1    Spain  27.0  48000.0     center       Yes
2  Germany  30.0  54000.0  northwest        No
3    Spain  38.0  61000.0        sud        No
4  Germany  40.0      NaN        est       Yes

In [ ]:
smoking.head(5)

gender  age marital_status highest_qualification nationality ethnicity  \
0    Male   38       Divorced      No Qualification     British     White   
1  Female   42         Single      No Qualification     British     White   
2    Male   40        Married                Degree     English     White   
3  Female   40        Married                Degree     English     White   
4  Female   39        Married          GCSE/O Level     British     White   

       gross_income     region smoke  amt_weekends  amt_weekdays     type  
0    2,600 to 5,200  The North    No           NaN           NaN      NaN  
1       Under 2,600  The North   Yes          12.0          12.0  Packets  
2  28,600 to 36,400  The North    No           NaN           NaN      NaN  
3  10,400 to 15,600  The North    No           NaN           NaN      NaN  
4    2,600 to 5,200  The North    No           NaN           NaN      NaN

In [ ]:
salaryData.head(5)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

<center><h2>Traitement des valeurs manquantes<h2></center>

<center>Compter les valeurs manquantes dans chaque dataset</center>

In [ ]:
data.isna().sum()

Country      0
Age          1
Salary       1
Region       0
Purchased    0
dtype: int64

In [ ]:
"""
Donc on a les repartions suivantes:
- colonne country : 0 valeur manquante
- colonne Age : une valeur manquante
- colonne purchased : 0 valeur manquante
"""

'\nDonc on a les repartions suivantes:\n- colonne country : 0 valeur manquante\n- colonne Age : une valeur manquante\n- colonne purchased : 0 valeur manquante\n'

In [ ]:
salaryData.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

In [ ]:
smoking.isna().sum()

gender                      0
age                         0
marital_status              0
highest_qualification       0
nationality                 0
ethnicity                   0
gross_income                0
region                      0
smoke                       0
amt_weekends             1270
amt_weekdays             1270
type                     1270
dtype: int64

<center>Remplacement des valeurs manquantes contenues dans le jeud de donnée data par la moyenne</center>

In [ ]:
data["Age"] = data["Age"].fillna(data["Age"].mean())

data["Salary"] = data["Salary"].fillna(data["Salary"].mean())

data.isna().sum()

Country      0
Age          0
Salary       0
Region       0
Purchased    0
dtype: int64

In [ ]:
data.head(5)

Country   Age        Salary     Region Purchased
0   France  44.0  72000.000000      ouest        No
1    Spain  27.0  48000.000000     center       Yes
2  Germany  30.0  54000.000000  northwest        No
3    Spain  38.0  61000.000000        sud        No
4  Germany  40.0  63777.777778        est       Yes

<center>Cas du jeu de données smoking</cente>

In [ ]:
"""
Les valeurs manquantes que l'on doit traiter sont dans les colonnes :
'amt_weekends' , 'amt_weekdays' et 'type'.
les valeurs des variables des colonnes 'amt_weekends' et 'amt_weekdays' sont numeriques donc on peut remplacer les valeurs manquantes par la moyenne ou autre methode.
la colonn" 'type' quant a elle possede des valeur nominales, donc on peut utilisé le mode.
"""

'\nLes valeurs manquantes que l\'on doit traiter sont dans les colonnes :\n\'amt_weekends\' , \'amt_weekdays\' et \'type\'.\nles valeurs des variables des colonnes \'amt_weekends\' et \'amt_weekdays\' sont numeriques donc on peut remplacer les valeurs manquantes par la moyenne ou autre methode.\nla colonn" \'type\' quant a elle possede des valeur nominales, donc on peut utilisé le mode.\n'

In [ ]:
smoking["amt_weekends"] = smoking["amt_weekends"].fillna(smoking["amt_weekends"].mean())

smoking["amt_weekdays"] = smoking["amt_weekdays"].fillna(smoking["amt_weekdays"].mean())

smoking["type"] = smoking["type"].fillna(smoking["type"].mode()[0]) #mode()[0] permet de ree

smoking.head(5)

gender  age marital_status highest_qualification nationality ethnicity  \
0    Male   38       Divorced      No Qualification     British     White   
1  Female   42         Single      No Qualification     British     White   
2    Male   40        Married                Degree     English     White   
3  Female   40        Married                Degree     English     White   
4  Female   39        Married          GCSE/O Level     British     White   

       gross_income     region smoke  amt_weekends  amt_weekdays     type  
0    2,600 to 5,200  The North    No     16.410926     13.750594  Packets  
1       Under 2,600  The North   Yes     12.000000     12.000000  Packets  
2  28,600 to 36,400  The North    No     16.410926     13.750594  Packets  
3  10,400 to 15,600  The North    No     16.410926     13.750594  Packets  
4    2,600 to 5,200  The North    No     16.410926     13.750594  Packets

In [ ]:
smoking.isna().sum()

gender                   0
age                      0
marital_status           0
highest_qualification    0
nationality              0
ethnicity                0
gross_income             0
region                   0
smoke                    0
amt_weekends             0
amt_weekdays             0
type                     0
dtype: int64

<center>Recuperation des données pour les encoder et  normaliser et les diviser en jeux de test et d'entrainement</center>

In [ ]:
x_data = data.iloc[:, :-1] 
y_data = data.iloc[:, 4]

In [ ]:
x_data

Country        Age        Salary     Region
0   France  44.000000  72000.000000      ouest
1    Spain  27.000000  48000.000000     center
2  Germany  30.000000  54000.000000  northwest
3    Spain  38.000000  61000.000000        sud
4  Germany  40.000000  63777.777778        est
5   France  35.000000  58000.000000     center
6    Spain  38.777778  52000.000000      ouest
7   France  48.000000  79000.000000      ouest
8  Germany  50.000000  83000.000000        sud
9   France  37.000000  67000.000000   nortwest

In [ ]:
y_data

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelBinarizer, LabelEncoder

In [ ]:
#Encodons la colonne country de data avec labelEncoder

labelEncoder_data = LabelEncoder()
labelBinarizer = LabelBinarizer()
oneHotEncoder = OneHotEncoder()

x_data["Region"] = labelEncoder_data.fit_transform(x_data.loc[:, ["Region"]])

y_data = labelEncoder_data.fit_transform(y_data)

x_data["Country"] = oneHotEncoder.fit_transform(x_data.loc[:, ["Country"]]).toarray()

x_data

/home/kevin/.local/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Country        Age        Salary  Region
0      1.0  44.000000  72000.000000       5
1      0.0  27.000000  48000.000000       1
2      0.0  30.000000  54000.000000       3
3      0.0  38.000000  61000.000000       0
4      0.0  40.000000  63777.777778       2
5      1.0  35.000000  58000.000000       1
6      0.0  38.777778  52000.000000       5
7      1.0  48.000000  79000.000000       5
8      0.0  50.000000  83000.000000       6
9      1.0  37.000000  67000.000000       4

In [ ]:
y_data

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#normalisation des données

x_StandardScaler = StandardScaler()

x_dataset = x_data[["Country", "Age", "Salary", "Region"]].values

y_dataset = y_data
x_dataset

array([[1.00000000e+00, 4.40000000e+01, 7.20000000e+04, 5.00000000e+00],
       [0.00000000e+00, 2.70000000e+01, 4.80000000e+04, 1.00000000e+00],
       [0.00000000e+00, 3.00000000e+01, 5.40000000e+04, 3.00000000e+00],
       [0.00000000e+00, 3.80000000e+01, 6.10000000e+04, 0.00000000e+00],
       [0.00000000e+00, 4.00000000e+01, 6.37777778e+04, 2.00000000e+00],
       [1.00000000e+00, 3.50000000e+01, 5.80000000e+04, 1.00000000e+00],
       [0.00000000e+00, 3.87777778e+01, 5.20000000e+04, 5.00000000e+00],
       [1.00000000e+00, 4.80000000e+01, 7.90000000e+04, 5.00000000e+00],
       [0.00000000e+00, 5.00000000e+01, 8.30000000e+04, 6.00000000e+00],
       [1.00000000e+00, 3.70000000e+01, 6.70000000e+04, 4.00000000e+00]])

In [ ]:
x_dataset = x_StandardScaler.fit_transform(x_dataset)

x_dataset

array([[ 1.22474487e+00,  7.58874362e-01,  7.49473254e-01,
         9.04534034e-01],
       [-8.16496581e-01, -1.71150388e+00, -1.43817841e+00,
        -1.10554160e+00],
       [-8.16496581e-01, -1.27555478e+00, -8.91265492e-01,
        -1.00503782e-01],
       [-8.16496581e-01, -1.13023841e-01, -2.53200424e-01,
        -1.60806050e+00],
       [-8.16496581e-01,  1.77608893e-01,  6.63219199e-16,
        -6.03022689e-01],
       [ 1.22474487e+00, -5.48972942e-01, -5.26656882e-01,
        -1.10554160e+00],
       [-8.16496581e-01,  0.00000000e+00, -1.07356980e+00,
         9.04534034e-01],
       [ 1.22474487e+00,  1.34013983e+00,  1.38753832e+00,
         9.04534034e-01],
       [-8.16496581e-01,  1.63077256e+00,  1.75214693e+00,
         1.40705294e+00],
       [ 1.22474487e+00, -2.58340208e-01,  2.93712492e-01,
         4.02015126e-01]])

<center>Divisons le jeu de données en testset et trainset</center>

In [ ]:
from sklearn.model_selection import train_test_split

X_train, x_test, Y_train, y_test = train_test_split(x_dataset, y_dataset, test_size=0.2, random_state=0)#random_state=0 permet d'optenir toujours le meme echantillon

In [ ]:
X_train

array([[-8.16496581e-01,  1.77608893e-01,  6.63219199e-16,
        -6.03022689e-01],
       [ 1.22474487e+00, -2.58340208e-01,  2.93712492e-01,
         4.02015126e-01],
       [-8.16496581e-01, -1.71150388e+00, -1.43817841e+00,
        -1.10554160e+00],
       [-8.16496581e-01,  0.00000000e+00, -1.07356980e+00,
         9.04534034e-01],
       [ 1.22474487e+00,  1.34013983e+00,  1.38753832e+00,
         9.04534034e-01],
       [-8.16496581e-01, -1.13023841e-01, -2.53200424e-01,
        -1.60806050e+00],
       [ 1.22474487e+00,  7.58874362e-01,  7.49473254e-01,
         9.04534034e-01],
       [ 1.22474487e+00, -5.48972942e-01, -5.26656882e-01,
        -1.10554160e+00]])

In [ ]:
x_test

array([[-0.81649658, -1.27555478, -0.89126549, -0.10050378],
       [-0.81649658,  1.63077256,  1.75214693,  1.40705294]])

In [ ]:
Y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [ ]:
y_test

array([0, 0])

In [ ]:
"""
par la suite  vousn'avez qu'a passer les données a votre modele pour l'entrainer
"""

"\npar la suite  vousn'avez qu'a passer les données a votre modele pour l'entrainer\n"

<center>Implementons le principe de validation croisée</center>

In [ ]:
from sklearn.model_selection import KFold