<center><h3>Régression linéaire multiple<h3></center>

In [1]:
#Importation des bibiotheques

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import  accuracy_score, mean_absolute_error, mean_squared_error
import numpy as np

In [ ]:
PositionSalary = pd.read_csv("./../../Datasets/Position_Salaries.csv")

PositionSalary.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

<center>Prétraitement des données</center>

In [3]:
StartupsData.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

Verification que chaque colonne ne contient pas de valeurs manquantes

In [4]:
StartupsData["R&D Spend"].isna().sum()

0

In [5]:
StartupsData["Administration"].isna().sum()

0

In [6]:
StartupsData["Marketing Spend"].isna().sum()

0

In [7]:
StartupsData["State"].isna().sum()

0

In [8]:
StartupsData["Profit"].isna().sum()

0

encodage de la colonne State avec le OneHotEncoder

In [9]:
from sklearn.preprocessing import OneHotEncoder

oneHotEncoder = OneHotEncoder()

StartupsData["State"] = oneHotEncoder.fit_transform(StartupsData.loc[:, ["State"]]).toarray()

In [10]:
StartupsData

R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.20       136897.80        471784.10    0.0  192261.83
1   162597.70       151377.59        443898.53    1.0  191792.06
2   153441.51       101145.55        407934.54    0.0  191050.39
3   144372.41       118671.85        383199.62    0.0  182901.99
4   142107.34        91391.77        366168.42    0.0  166187.94
5   131876.90        99814.71        362861.36    0.0  156991.12
6   134615.46       147198.87        127716.82    1.0  156122.51
7   130298.13       145530.06        323876.68    0.0  155752.60
8   120542.52       148718.95        311613.29    0.0  152211.77
9   123334.88       108679.17        304981.62    1.0  149759.96
10  101913.08       110594.11        229160.95    0.0  146121.95
11  100671.96        91790.61        249744.55    1.0  144259.40
12   93863.75       127320.38        249839.44    0.0  141585.52
13   91992.39       135495.07        252664.93    1.0  134307.35
14  119943.24       156547.42        256512.92    0.0  132602.65
15  114523.61       122616.84        261776.23    0.0  129917.04
16   78013.11       121597.55        264346.06    1.0  126992.93
17   94657.16       145077.58        282574.31    0.0  125370.37
18   91749.16       114175.79        294919.57    0.0  124266.90
19   86419.70       153514.11             0.00    0.0  122776.86
20   76253.86       113867.30        298664.47    1.0  118474.03
21   78389.47       153773.43        299737.29    0.0  111313.02
22   73994.56       122782.75        303319.26    0.0  110352.25
23   67532.53       105751.03        304768.73    0.0  108733.99
24   77044.01        99281.34        140574.81    0.0  108552.04
25   64664.71       139553.16        137962.62    1.0  107404.34
26   75328.87       144135.98        134050.07    0.0  105733.54
27   72107.60       127864.55        353183.81    0.0  105008.31
28   66051.52       182645.56        118148.20    0.0  103282.38
29   65605.48       153032.06        107138.38    0.0  101004.64
30   61994.48       115641.28         91131.24    0.0   99937.59
31   61136.38       152701.92         88218.23    0.0   97483.56
32   63408.86       129219.61         46085.25    1.0   97427.84
33   55493.95       103057.49        214634.81    0.0   96778.92
34   46426.07       157693.92        210797.67    1.0   96712.80
35   46014.02        85047.44        205517.64    0.0   96479.51
36   28663.76       127056.21        201126.82    0.0   90708.19
37   44069.95        51283.14        197029.42    1.0   89949.14
38   20229.59        65947.93        185265.10    0.0   81229.06
39   38558.51        82982.09        174999.30    1.0   81005.76
40   28754.33       118546.05        172795.67    1.0   78239.91
41   27892.92        84710.77        164470.71    0.0   77798.83
42   23640.93        96189.63        148001.11    1.0   71498.49
43   15505.73       127382.30         35534.17    0.0   69758.98
44   22177.74       154806.14         28334.72    1.0   65200.33
45    1000.23       124153.04          1903.93    0.0   64926.08
46    1315.46       115816.21        297114.46    0.0   49490.75
47       0.00       135426.92             0.00    1.0   42559.73
48     542.05        51743.15             0.00    0.0   35673.41
49       0.00       116983.80         45173.06    1.0   14681.40

Nous n'aurons pas besoin de normaliser les données ici catr il s'agit d'une regression linéaire et les libraries le feront pour nous

In [11]:
X = StartupsData.iloc[:, :-1].values
Y = StartupsData.iloc[:, 4].values

In [12]:
X

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 0.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 1.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 0.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 0.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 0.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 0.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 1.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 0.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 0.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 1.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 0.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 1.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 0.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 1.0000000e+00],
       [1.1994324e+05, 1.5654742e+

Séparation du jeu de données

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=0)

In [50]:
print(X.shape)  # Affiche la forme de X  
print(Y.shape)  # Affiche la forme de Y

(50, 5)
(50,)


appliquons la regression linéaire multiple

In [14]:
from sklearn.linear_model import LinearRegression

linearRegression = LinearRegression()

linearRegression.fit(X_train, y_train)

LinearRegression()

Prédiction

In [15]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56])

In [16]:
y_pred = linearRegression.predict(X_test)

y_pred

array([103962.55391373, 132569.79621934, 133248.38608834,  72577.20448177,
       179058.65635572, 114748.39099366,  66688.37917583,  98150.25103157])

In [17]:
score = mean_squared_error(y_test, y_pred)
score

97581277.90779126

<center><h2>BackWard Élimination</h2></center>

<center>Appliquons le BackWard Élimination pour eliminer les variables qui n'ont pas un grand imapct sur la variable dependante profit</center>

Ici, on va concatener le dataset avec une colonne de 1 a la premeiere colonne du dataset pour que on ait quelque chose de la forme :

Y = b0*X0 + b1*X1 + b2*X2 + ... + bn*Xn

ou Xi est la  variable independante 
bi est le coefficient 
Y est la variable dependante

car au depat on avait:

Y = b0 + b1*X1 + b2*X2 + ... + bn*Xn 

et donc comme on veut avoir le cofficient de chaque vaiable independante, on a pensé a ajouter une colonne de 1 au debut du dataset qui serait equivaut a X0 pour qu'on aiyt l'expression:  

Y = b0*X0 + b1*X1 + b2*X2 + ... + bn*Xn

In [18]:
size = len(Y)

In [19]:
X = np.append( arr=np.ones((size, 1)).astype(int), values=X, axis=1 )
X

array([[1.0000000e+00, 1.6534920e+05, 1.3689780e+05, 4.7178410e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.6259770e+05, 1.5137759e+05, 4.4389853e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.5344151e+05, 1.0114555e+05, 4.0793454e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.4437241e+05, 1.1867185e+05, 3.8319962e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.4210734e+05, 9.1391770e+04, 3.6616842e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.3187690e+05, 9.9814710e+04, 3.6286136e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.3461546e+05, 1.4719887e+05, 1.2771682e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.3029813e+05, 1.4553006e+05, 3.2387668e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.2054252e+05, 1.4871895e+05, 3.1161329e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.2333488e+05, 1.0867917e+05, 3.0498162e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.0191308e+05, 1.1059411e+05, 2.2916095e+05,
        0.00

In [27]:
#Créons une matrice X_optimale qui contiuendra les variables qui apportent une importance siginificative a notre modele

X_optimale = X[:, [0, 1, 2, 3, 4]] #Recuperer toutes les colonnes du dataset X
X_optimale


array([[1.0000000e+00, 1.6534920e+05, 1.3689780e+05, 4.7178410e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.6259770e+05, 1.5137759e+05, 4.4389853e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.5344151e+05, 1.0114555e+05, 4.0793454e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.4437241e+05, 1.1867185e+05, 3.8319962e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.4210734e+05, 9.1391770e+04, 3.6616842e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.3187690e+05, 9.9814710e+04, 3.6286136e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.3461546e+05, 1.4719887e+05, 1.2771682e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.3029813e+05, 1.4553006e+05, 3.2387668e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.2054252e+05, 1.4871895e+05, 3.1161329e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.2333488e+05, 1.0867917e+05, 3.0498162e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.0191308e+05, 1.1059411e+05, 2.2916095e+05,
        0.00

In [28]:

"""#+
This function performs Ordinary Least Squares (OLS) regression using the statsmodels library.#+
#+
Parameters:#+
- endog (array-like): The dependent variable, a 1-D array-like object.#+
- exog (array-like): The independent variables, a 2-D array-like object.#+
#+
Returns:#+
- regressor_OLS: An instance of the statsmodels.regression.linear_model.OLS class, which represents the OLS regression model.#+
#+
The function takes the endogenous (dependent) variable 'Y' and the exogenous (independent) variables 'X_optimale' as input and fits an OLS regression model.#+
"""#+


"#+\nThis function performs Ordinary Least Squares (OLS) regression using the statsmodels library.#+\n#+\nParameters:#+\n- endog (array-like): The dependent variable, a 1-D array-like object.#+\n- exog (array-like): The independent variables, a 2-D array-like object.#+\n#+\nReturns:#+\n- regressor_OLS: An instance of the statsmodels.regression.linear_model.OLS class, which represents the OLS regression model.#+\n#+\nThe function takes the endogenous (dependent) variable 'Y' and the exogenous (independent) variables 'X_optimale' as input and fits an OLS regression model.#+\n"

<center>BackWard Elimination </br><h2>Étape 1</h2></br><h3>Selectionner les seuil SL(exemple : SL =0.05) en dessous du quel on conserve une variable dans le model</h3></center>

<center>BackWard Elimination </br><h2>Étape 2</h2></br><h3>Entrainer le model avec tous les predicteurs possibles</h3></center>

In [29]:
import statsmodels.api as sm

regressor_OLS = sm.OLS(endog=Y, exog=X_optimale).fit()


<center>BackWard Elimination </br><h2>Étape 3</h2></br><h3>Conserver le prédicteur avec la plus grande P-value, si P > SL aller a l'etape 4 sinon Aller a l'etape 5</br> P ici est la probabilité que le coefficient d'une variable soit nul </h3></center>

In [30]:
regressor_OLS.summary() #Permet de retourner les tableaux de caracteristiques a l'interieur de laquelle on identifiera les p-Value

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                lun, 03 mar 2025   Prob (F-statistic):           8.51e-29
Time:                        14:44:24   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.016e+04   6798.992      7.377      0.000    3.65e+04    6.39e+04
x1             0.8057      0.046     17.646      0.000       0.714       0.898
x2            -0.0268      0.052     -0.520      0.606      -0.131       0.077
x3             0.0272      0.017      1.627      0.111      -0.006       0.061
x4           -70.2265   2828.752     -0.025      0.980   -5767.625    5627.172
==============================================================================
Omnibus:                       14.785   Durbin-Watson:                   1.281
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.242
Skew:                          -0.949   Prob(JB):                     2.44e-05
Kurtosis:                       5.568   Cond. No.                     1.44e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.44e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Dans le trableau fournit par cette methode (regressor_OLS.summary()) 

- la ligne "const" represente celle que l'on a ajouter dans notre dataset(X) en premiere colonne.

- les Xi sont les variables dans le meme ordre que dans le dataset

- la colonne P > |t

<center>BackWard Elimination </br><h2>Étape 4</h2></br><h3>Retirer la variable dont la P-value est superieur au seuil dans le jeu de données.</h3></center>

In [33]:
#Retirer la variable X4 car sa p value est de 0.980	> 0.05

X_optimale = X[:, [0, 1, 2, 3]]

<center>BackWard Elimination </br><h2>Étape 5</h2></br><h3>Entrainer le model sans la variable don le P > SL</h3></center>

In [34]:
regressor_OLS = sm.OLS(endog=Y, exog=X_optimale).fit()

In [35]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                lun, 03 mar 2025   Prob (F-statistic):           4.53e-30
Time:                        14:45:26   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

<center>BackWard Elimination </br><h2>Étape 4</h2></br><h3>Retirer la variable dont la P-value est superieur au seuil dans le jeu de données.</h3></center>

In [36]:
#Retirer la variable X2 car sa p value est de 0.606	> 0.05

X_optimale = X[:, [0, 1, 3]]

In [37]:
regressor_OLS = sm.OLS(endog=Y, exog=X_optimale).fit()

regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                lun, 03 mar 2025   Prob (F-statistic):           2.16e-31
Time:                        14:48:30   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

on peut eliminer la variable X2 car sa P-value est 0.06 > 0.05 mais laissons la histoire de pratique, Ainsi la combinaison des variables qui permettent de bien predire les profit est composé des variables X1(R&D Spend) et X2(Marketing Spend)

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X_optimale, Y, test_size=0.15, random_state=0)

In [54]:


finalRegressor = LinearRegression()

finalRegressor.fit(X_train, y_train)

LinearRegression()

In [55]:
final_Y_predict = finalRegressor.predict(X_test)
final_Y_predict

array([102233.23565958, 133606.98920513, 133949.0507749 ,  73572.88757331,
       180116.44892447, 114279.85967514,  68172.55388282,  97431.12261484])

In [56]:
new_score = mean_squared_error(y_test, final_Y_predict)
new_score #Nous voyons que le taux d'erreur a diminué

82075053.37708801